# Nome do Workflow
name: Hack10 Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - pipedev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup React
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: npm install

      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
        run: | 
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}

      - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          CLOUD_SQL_USERNAME: ${{ secrets.CLOUD_SQL_USERNAME }}
          CLOUD_SQL_PASSWORD: ${{ secrets.CLOUD_SQL_PASSWORD }}
          CLOUD_SQL_DATABASE_NAME: ${{ secrets.CLOUD_SQL_DATABASE_NAME }}
          DB_LOCAL_HOST: ${{ secrets.DB_LOCAL_HOST }}
          CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        run: | 
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myweb:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myweb:latest               