# Nome do Workflow
name: Hack10 Pipeline WEB

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - pipedev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup React
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
        run: | 
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}

      - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: | 
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/web:latest --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} .
          docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/web:latest          

  DeployProd:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to Cloud
        id: cloudrunweb
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'hack10-cloud-run-web'
          image: ${{ secrets.ARTIFACT_REGISTRY_REPO }}/web:latest