# Nome do Workflow
name: Hack10 Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - pipedev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup React
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: npm install